#!/bin/bash

echo "Mirroring "$1
nohup wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=unix \
     --domains $1 \
     --no-parent \
     --wait=5 \
     --limit-rate=1000K $1 &

